const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART";
const CLEAR_CART = "CLEAR_CART";
const GET_CART_BY_ID = "GET_CART_BY_ID";
const UPDATE_CART_QUANTITY = "UPDATE_CART_QUANTITY";

module.exports = {
  ADD_TO_CART,
  REMOVE_FROM_CART,
  CLEAR_CART,
  GET_CART_BY_ID,
  UPDATE_CART_QUANTITY,
};
