const ORDER_ALPHABETIC = " ORDER_ALPHABETIC";
const ORDER_PRICE = " ORDER_PRICE";
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
const CREATE_PRODUCT = "CREATE_PRODUCT";
const FILTER_TYPE = " FILTER_TYPE";
const FILTER_CATEGORY = "FILTER_CATEGORY";
const RESET_FILTERS = "RESET_FILTERS";
const GET_BY_NAME = "GET_BY_NAME";
const GET_BY_ID = "GET_BY_ID";
const FILTER_CATEGORY_AND_TYPE = "FILTER_CATEGORY_AND_TYPE";
const CLEAR_STATE = "CLEAR_STATE";

module.exports = {
    ORDER_ALPHABETIC,
    ORDER_PRICE,
    GET_ALL_PRODUCTS,
    GET_BY_NAME,
    GET_BY_ID,
    CREATE_PRODUCT,
    FILTER_TYPE,
    FILTER_CATEGORY,
    RESET_FILTERS,
    FILTER_CATEGORY_AND_TYPE,
    CLEAR_STATE,
};
