 
const  ORDER_ALPHABETIC = " ORDER_ALPHABETIC"
const  ORDER_PRICE = " ORDER_PRICE"
const  FILTER_TYPE = " FILTER_TYPE"
const  FILTER_CATEGORY = "FILTER_CATEGORY"

module.exports = {
    ORDER_ALPHABETIC,
    ORDER_PRICE,
    FILTER_TYPE,
    FILTER_CATEGORY
}