const  ORDER_ALPHABETIC = " ORDER_ALPHABETIC"
const  ORDER_PRICE = " ORDER_PRICE"
const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS"
const CREATE_PRODUCT = "CREATE_PRODUCT"
const  FILTER_TYPE = " FILTER_TYPE"
const  FILTER_CATEGORY = "FILTER_CATEGORY"

module.exports = {
    ORDER_ALPHABETIC,
    ORDER_PRICE,
    GET_ALL_PRODUCTS,
    CREATE_PRODUCT,
    FILTER_TYPE,
    FILTER_CATEGORY
}