const POST_USERS = "POST_USERS";
const GET_USERS = "GET_USERS";
const UPDATE_USER = "UPDATE_USER";
const SET_USER = "SET_USER";
const USER_BY_NAME = "USER_BY_NAME";
const USER_ORDER_ALPHABETIC = "USER_ORDER_ALPHABETIC";

module.exports = {
  POST_USERS,
  GET_USERS,
  UPDATE_USER,
  SET_USER,
  USER_BY_NAME,
  USER_ORDER_ALPHABETIC
};
